# permissions for end users to view materials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: material-viewer-role
rules:
- apiGroups:
  - base.tapchain.org
  resources:
  - materials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - base.tapchain.org
  resources:
  - materials/status
  verbs:
  - get
