# permissions for end users to edit materials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: material-editor-role
rules:
- apiGroups:
  - base.tapchain.org
  resources:
  - materials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.tapchain.org
  resources:
  - materials/status
  verbs:
  - get
