# permissions for end users to edit materialclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: materialclass-editor-role
rules:
- apiGroups:
  - base.tapchain.org
  resources:
  - materialclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.tapchain.org
  resources:
  - materialclasses/status
  verbs:
  - get
