
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - base.tapchain.org
  resources:
  - generatorclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.tapchain.org
  resources:
  - generatorclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - base.tapchain.org
  resources:
  - materialclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.tapchain.org
  resources:
  - materialclasses/status
  verbs:
  - get
  - patch
  - update
